// Internal build stamp: bumps package.json's patch level, captures the
// current git short SHA + dirty-tree state, and writes src/version.js so the
// app UI can display "v2.1.7 · 95c616d" in the header. Runs as the first
// step of `npm run build`. Each build = one patch bump = one identifier.
//
// The bumped package.json is left as an uncommitted working-tree change;
// commit it whenever you commit the substantive work that justifies the bump.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const pkgPath = path.join(repoRoot, 'package.json');
const versionOutPath = path.join(repoRoot, 'src', 'version.js');

// 1. Bump patch level
const pkgRaw = fs.readFileSync(pkgPath, 'utf8');
const pkg = JSON.parse(pkgRaw);
const parts = String(pkg.version).split('.').map(Number);
if (parts.length !== 3 || parts.some(n => !Number.isFinite(n))) {
    console.error(`[stamp-version] package.json version "${pkg.version}" is not three-part semver — aborting`);
    process.exit(1);
}
parts[2] += 1;
const newVersion = parts.join('.');
pkg.version = newVersion;
// Preserve the file's existing 4-space indent + trailing newline
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 4) + '\n');

// 2. Capture git info — tolerate non-git checkouts
let sha = 'nogit';
let dirty = false;
try {
    sha = execSync('git rev-parse --short HEAD', { cwd: repoRoot, encoding: 'utf8' }).trim() || 'nogit';
    const status = execSync('git status --porcelain', { cwd: repoRoot, encoding: 'utf8' }).trim();
    // The patch bump we just made will appear in status — filter it out so
    // an otherwise-clean tree doesn't get flagged as dirty.
    const otherChanges = status.split('\n').filter(l => l && !l.endsWith('package.json'));
    dirty = otherChanges.length > 0;
} catch { /* not a git repo or git unavailable */ }

const buildDate = new Date().toISOString();

const out = `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(newVersion)};
export const APP_BUILD_SHA = ${JSON.stringify(sha)};
export const APP_BUILD_DIRTY = ${JSON.stringify(dirty)};
export const APP_BUILD_DATE = ${JSON.stringify(buildDate)};
`;
fs.writeFileSync(versionOutPath, out);

console.log(`[stamp-version] v${newVersion} · ${sha}${dirty ? ' (dirty)' : ''}`);
