// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const APP_VERSION = "2.2.8";
export const APP_BUILD_SHA = "6fb171f";
export const APP_BUILD_DIRTY = true;
export const APP_BUILD_DATE = "2026-05-14T17:34:56.587Z";
