// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const APP_VERSION = "2.1.3";
export const APP_BUILD_SHA = "888dd68";
export const APP_BUILD_DIRTY = true;
export const APP_BUILD_DATE = "2026-05-13T14:14:12.798Z";
