// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const APP_VERSION = "2.2.7";
export const APP_BUILD_SHA = "d638e1b";
export const APP_BUILD_DIRTY = true;
export const APP_BUILD_DATE = "2026-05-14T17:30:04.373Z";
